version: '3.8'

services:
  clash-to-singbox:
    build: .
    container_name: clash-to-singbox-converter
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    networks:
      - converter-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  converter-network:
    driver: bridge 